# TP 2022 configuration.

logPath: log_config_tp_2022.txt

invariantLimit: 1000

initialMarking: [0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 2, 2, 3, 1, 2, 1]

incidence:
  #    T1  T2  T3  T4  T5  T6  T7  T8  T9  T10 T11 T12
  - [1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0] # P1
  - [0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0] # P2
  - [0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0] # P3
  - [0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0] # P4
  - [0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0] # P5
  - [0, 0, 0, 0, 0, 1, 1, -1, 0, 0, 0, 0] # P6
  - [-1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0] # P7
  - [0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0] # P8
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0] # P9
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1] # P10
  - [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 1] # P11
  - [-1, 1, 1, 0, 0, 0, 0, 0, 0, 0, -1, 1] # P12
  - [0, -1, -1, 1, 1, 0, 0, 0, 0, -1, 1, 0] # P13
  - [0, 0, 0, -1, -1, 1, 1, 0, -1, 1, 0, 0] # P14
  - [0, 0, 0, 0, 0, -1, -1, 1, 0, 0, 0, 0] # P15
  - [0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0, 0] # P16
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 1, 0] # P17

timeRanges:
  # Selected: alpha = 10 ms, beta = 5000 ms
  - [0, 0] # T1
  - [0, 0] # T2
  - [0, 0] # T3
  - [10, 5000] # T4
  - [10, 5000] # T5
  - [10, 5000] # T6
  - [10, 5000] # T7
  - [10, 5000] # T8
  - [0, 0] # T9
  - [10, 5000] # T10
  - [10, 5000] # T11
  - [10, 5000] # T12

  # Alternatives:
  # - alpha = 15 ms, beta = 3000 ms
  # - alpha = 1 ms, beta = 5000 ms
  # - alpha = 100 ms, beta = 5000 ms

segments:
  - name: Segment-1
    threadQuantity: 2
    transitions: [0]

  - name: Segment-2
    threadQuantity: 4
    transitions: [1, 3, 5]

  - name: Segment-3
    threadQuantity: 4
    transitions: [2, 4, 6]

  - name: Segment-4
    threadQuantity: 1
    transitions: [7]

  - name: Segment-5
    threadQuantity: 4
    transitions: [8, 9, 10, 11]

policy: random
